name: CI

on:
  create:
    tags: [ v* ]
  push:
    branches: [ master ]
    tags: [ v* ]
  pull_request:
    branches: [ master ]

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - uses: actions/checkout@v2

    - name: Build
      run: make build

  test:
    needs: compile

    runs-on: ubuntu-latest

    steps:
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - uses: actions/checkout@v2

    - name: Run tests
      run: make test
  
  publish:
    needs: test

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)

      - name: Build docker image
        run: make docker VERSION=$VERSION
        env:
          VERSION: ${{ steps.get_version.outputs.VERSION }}

      - name: Log into registry
        run: echo "$PASSWORD" | docker login -u $USERNAME --password-stdin
        env:
          REGISTRY: scnewma
          USERNAME: ${{ secrets.DOCKER_USERNAME }}
          PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Publish docker image
        run: make docker-publish VERSION=$VERSION
        env:
          VERSION: ${{ steps.get_version.outputs.VERSION }}